### ISSUE TITLE
Feedback - Missing few key properties like Width, Visible, etc 

### ISSUE THREAD

**Issue by venkatagolla1** [GorgonUK/Modern-Data-Grid#1]
Firstly, thank you for your efforts on this component. It looks fantastic! However, it is missing a few key properties such as column width, visibility, etc.

Issues:

- Data does not refresh unless you change screens.
- Selection is not working.
- Date columns display the full date with the time zone.
- Choice columns display their enum values.
- Currency fields are displayed as decimals.
- Only 25 rows are displayed by default, regardless of the “Default rows” setting.

**Comment by GorgonUK** [comment]
Hi @venkatagolla1 thank you for raising this. I will try to work through them one by one.
